config/routes.rb
Rails.application.routes.draw do
  root 'repositories#index'

  resources :repositories do
    resources :item_files, only: [:show, :new, :create, :destroy]
    resources :item_scripts, only: [:show, :new, :create, :destroy]
  end
end

app/models/concerns/item.rb
module Item
  extend ActiveSupport::Concern

  included do
    field :name, type: String
    field :source_file, type: String

    validates_presence_of :name, :source_file

    embedded_in :repository

    mount_base64_uploader :source_file, SourceUploader
  end
end

app/models/item_file.rb
class ItemFile
  include Mongoid::Document
  include Item
end

app/models/item_script.rb
class ItemScript
  include Mongoid::Document
  include Item

  field :command, type: String

  validates_presence_of :command
end

app/models/repository.rb
class Repository
  include Mongoid::Document
  field :name, type: String

  validates_presence_of :name

  embeds_many :item_files
  embeds_many :item_scripts
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/concerns/item_type_checking.rb
module ItemTypeChecking
  extend ActiveSupport::Concern

  def self.set_item(controller_class_name, repository, request)
    repository.method(NameHelper.tableize(controller_class_name)).call.find(request.params[:id])
  end

  def self.build_new_item(controller_class_name, repository, request)
    items = NameHelper.tableize(controller_class_name)
    model = NameHelper.underscore(controller_class_name)
    repository.method(items).call.build(request.params[model.to_sym])
  end

  def self.build_to_create_item(controller_class_name, repository, item_params)
    repository.method(NameHelper.tableize(controller_class_name)).call.build(item_params)
  end
end

app/controllers/concerns/items_controller.rb
module ItemsController
  extend ActiveSupport::Concern
  include ItemTypeChecking

  included do
    before_action :set_repository, only: [:show, :new, :create, :destroy]
    before_action :set_item, only: [:show, :destroy]

    def show
      @file_content = File.read("#{Rails.root}/public" + @item.source_file.to_s)
    end

    def new
      @new_item = ItemTypeChecking.build_new_item(self.class, @repository, request)
    end

    def create
      @new_item = ItemTypeChecking.build_to_create_item(self.class, @repository, item_params)
      respond_to do |format|
        if @new_item.save
          format.html { redirect_to @repository, notice: 'Item was successfully uploaded.' }
          format.json { render :show, status: :created, location: @repository }
        else
          format.html { render :new }
          format.json { render json: @repository.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @item.destroy

      respond_to do |format|
        format.html { redirect_to repository_url(@repository), notice: 'Item was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def set_repository
      @repository = Repository.find(params[:repository_id])
    end

    def set_item
      @item = ItemTypeChecking.set_item(self.class, @repository, request)
    end
  end
end

app/controllers/item_files_controller.rb
class ItemFilesController < ApplicationController
  include ItemsController

  private

  def item_params
    params.require(:item_file).permit(:name, :source_file)
  end
end

app/controllers/item_scripts_controller.rb
class ItemScriptsController < ApplicationController
  include ItemsController

  private

  def item_params
    params.require(:item_script).permit(:name, :source_file, :command)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_repository, only: [:show, :new, :create, :destroy]
  before_action :set_item, only: [:show, :destroy]

  def show
    @file_content = File.read("#{Rails.root}/public" + @item.source_file.to_s)
  end

  def new
    @new_item = @repository.items.build(params[:item])
  end

  def create
    @new_item = @repository.items.build(item_params)

    respond_to do |format|
      if @new_item.save
        format.html { redirect_to @repository, notice: 'Item was successfully uploaded.' }
        format.json { render :show, status: :created, location: @repository }
      else
        format.html { render :new }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to repository_url(@repository), notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def item_params
      params.require(:item).permit(:name, :source_file, :type, :command)
  end

  def set_repository
    @repository = Repository.find(params[:repository_id])
  end

  def set_item
    @item = @repository.items.find(params[:id])
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  # respond_to :json

  before_action :set_repository, only: [:show, :edit, :update, :destroy]

  # GET /repositories
  # GET /repositories.json
  def index
    # render json: Repository.all
    # respond_with Repository.all
    @repositories = Repository.all
  end

  # GET /repositories/1
  # GET /repositories/1.json
  def show
    @item_files = @repository.item_files
    @item_scripts = @repository.item_scripts
  end

  # GET /repositories/new
  def new
    @repository = Repository.new
  end

  # GET /repositories/1/edit
  def edit
  end

  # POST /repositories
  # POST /repositories.json
  def create
    @repository = Repository.new(repository_params)

    respond_to do |format|
      if @repository.save
        format.html { redirect_to @repository, notice: 'Repository was successfully created.' }
        format.json { render :show, status: :created, location: @repository }
      else
        format.html { render :new }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repositories/1
  # PATCH/PUT /repositories/1.json
  def update
    respond_to do |format|
      if @repository.update(repository_params)
        format.html { redirect_to @repository, notice: 'Repository was successfully updated.' }
        format.json { render :show, status: :ok, location: @repository }
      else
        format.html { render :edit }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1
  # DELETE /repositories/1.json
  def destroy
    @repository.destroy
    respond_to do |format|
      format.html { redirect_to repositories_url, notice: 'Repository was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repository
      @repository = Repository.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repository_params
      params.require(:repository).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_item_type(item)
    'script' if item.type == :script
    'file' if item.type == :file
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/item_files/_form.html.erb
<%= form_for [@repository, item_file], :html => {:id => "item_file_form"} do |form| %>
  <% if item_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item_file.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :item_file_name %>
  </div>

  <div class="field">
    <%= form.label :source_file %>
    <%= form.file_field :source_file, id: :item_file_source_file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<div id="repository" data-repository-id="<%= @repository._id %>">
</div>

app/views/item_files/_item_file.html.erb
<tr>
  <td><%= link_to item_file.name, repository_item_file_path(repository, item_file) %></td>
  <td></td>
  <td colspan="3"><%= link_to 'Destroy', repository_item_file_path(repository, item_file), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/item_files/new.html.erb
<h1><%= @repository.name %></h1>

<hr />

<h3>New File</h3>

<%= render 'form', item_file: @new_item %>

<%= link_to 'Back', repository_path(@repository) %>

app/views/item_files/show.html.erb
<h1><%= @item.name %> | <small><i>file</i></small></h1>

<hr />

<p><%= @file_content %></p>

<br />

<%= link_to 'Back', repository_path(@repository) %>

app/views/item_scripts/_form.html.erb
<%= form_for [@repository, item_script], :html => {:id => "item_script_form"} do |form| %>
  <% if item_script.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item_script.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item_script.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :item_script_name %>
  </div>

  <div class="field">
    <%= form.label :source_file %>
    <%= form.file_field :source_file, id: :item_script_source_file %>
  </div>

  <div class="field" id="command">
    <%= form.label :command %>
    <%= form.text_field :command, id: :item_script_command %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<div id="repository" data-repository-id="<%= @repository._id %>">
</div>

app/views/item_scripts/_item_script.html.erb
<tr>
  <td><%= link_to item_script.name, repository_item_script_path(repository, item_script) %></td>
  <td><%= item_script.command %></td>
  <td><%= link_to 'Destroy', repository_item_script_path(repository, item_script), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/item_scripts/new.html.erb
<h1><%= @repository.name %></h1>

<hr />

<h3>New Script</h3>

<%= render 'form', item_script: @new_item %>

<%= link_to 'Back', repository_path(@repository) %>

app/views/item_scripts/show.html.erb
<h1><%= @item.name %> | <small><i>script</i></small></h1>

<hr />

<p><%= @file_content %></p>

<br />

<%= link_to 'Back', repository_path(@repository) %>

app/views/items/new.html.erb
<h1><%= @repository.name %></h1>

<hr />

<h3>New Item</h3>

<%= render 'form', item: @new_item %>

<%= link_to 'Back', repository_path(@repository) %>

app/views/items/show.html.erb
<h1><%= @item.name %> | <small><i><%= @item.type %></i></small></h1>

<hr />

<p><%= @file_content %></p>

<br />

<%= link_to 'Back', repository_path(@repository) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="Repo">
  <head>
    <title>ReposMongo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/repositories/_form.html.erb
<%= form_with(model: repository, local: true, :html => {:id => "repository_form" }) do |form| %>
  <% if repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% repository.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :repository_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/repositories/_repository.html.erb
<tr>
  <td><%= link_to repository.name, repository %></td>
  <td><%= link_to 'Edit', edit_repository_path(repository) %></td>
  <td><%= link_to 'Destroy', repository, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/repositories/edit.html.erb
<h1>Editing Repository</h1>

<%= render 'form', repository: @repository %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Repositories</h1>

<hr />

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @repositories.each do |repository| %>
      <tr>
        <td><%= link_to repository.name, repository %></td>
        <td><%= link_to 'Edit', edit_repository_path(repository) %></td>
        <td><%= link_to 'Destroy', repository, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repository', new_repository_path %>

app/views/repositories/new.html.erb
<h1>New Repository</h1>

<%= render 'form', repository: @repository %>

<%= link_to 'Back', repositories_path %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<h1 id="repository" data-repository-id="<%= @repository._id %>">
  <%= @repository.name %>
</h1>

<hr />

<table id="items">
  <thead>
    <tr>
      <th>Name</th>
      <th>Command</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_scripts.each do |item_script| %>
      <tr>
        <td><%= link_to item_script.name, repository_item_script_path(@repository, item_script) %></td>
        <td><%= item_script.command %></td>
        <td><%= link_to 'Destroy', repository_item_script_path(@repository, item_script), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% @item_files.each do |item_file| %>
      <tr>
        <td><%= link_to item_file.name, repository_item_file_path(@repository, item_file) %></td>
        <td></td>
        <td><%= link_to 'Destroy', repository_item_file_path(@repository, item_file), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<strong><%= link_to 'New file', new_repository_item_file_path(@repository) %></strong> |
<strong><%= link_to 'New script', new_repository_item_script_path(@repository) %></strong>

<br />
<br />

<%= link_to 'Edit', edit_repository_path(@repository) %> |
<%= link_to 'Back', repositories_path %>